In [1]:
 #Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
import numpy as np
rand_num = np.random.normal(0,25,25)
print(rand_num)



[ -4.30777319  30.99707999  31.45854848 -16.94206493  36.92231364
  33.79711677  25.26682645  -0.08571273   6.68181415   6.1165092
  14.08561368   5.21059895  16.03393155 -21.87121442 -24.33282433
 -18.28562637  -1.45349916   2.64532166  -9.44513384   2.90816462
   2.96088937 -16.41201263 -25.61059424 -36.785938     1.54747733]


In [2]:
#Create an array of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [3]:
#declare a numpy array of values from 1 to 100 and make it into a 10*10 matrix.
arr1=np.arange(1,101).reshape(10,10)
print(arr1)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [4]:
#using the previously defined matrix print rows 1,5,6
print(arr1[1])
print(arr1[5])
print(arr1[6])

[11 12 13 14 15 16 17 18 19 20]
[51 52 53 54 55 56 57 58 59 60]
[61 62 63 64 65 66 67 68 69 70]


In [6]:
#using the previously defined matrix print elemnts from 3rd row  to 10th row
arr1[3:11,]

array([[ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [9]:
#using the previously defined matrix print all elemtnts from 4th column to 8th column
arr1[:,4:9]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49],
       [55, 56, 57, 58, 59],
       [65, 66, 67, 68, 69],
       [75, 76, 77, 78, 79],
       [85, 86, 87, 88, 89],
       [95, 96, 97, 98, 99]])

In [7]:
#using the same matrix print values from 3rd row 2nd coumn to 5th row 8th column
arr1[3:6,2:9]

array([[33, 34, 35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47, 48, 49],
       [53, 54, 55, 56, 57, 58, 59]])

In [8]:
#write a code to generate a 1000 random numbers each in the range(0,1) such that the count of all random points like are almost same .
array = np.random.randint(0,1,size=1000)
print(array);


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [10]:
#write the commands to get standard deviation, mean ,mode,median for a given vector 
import numpy
values = [99,86,87,88,111,86,103,87,94,78,77,85,86]

x = numpy.mean(values)

print(x)


89.76923076923077


In [11]:
y = numpy.median(values)
print(y)

87.0


In [12]:
from scipy import stats

z=stats.mode(values)
print(z)

ModeResult(mode=array([86]), count=array([3]))


In [13]:
import numpy as np
arr = [20, 2, 7, 1, 34]
np.std(arr)


12.576167937809991